
name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install libstdc++6
          sudo apt-get install libhttp-parser-dev
          sudo apt-get install libssh2-1-dev

      - name: Set up Node
        uses: actions/setup-node@v1

      - name: Install metadata validator
        run: wget https://github.com/loot/metadata-validator/releases/download/0.15.0/metadata-validator.tar.xz -O - | tar -xJ --strip-components=1

      - name: Install parser
        run: npm install -g js-yaml
